// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: alarm_center_video.proto
#ifndef GRPC_alarm_5fcenter_5fvideo_2eproto__INCLUDED
#define GRPC_alarm_5fcenter_5fvideo_2eproto__INCLUDED

#include "alarm_center_video.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace alarm_center_video {

class video_service GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::alarm_center_video::dev_info>> get_all_devs(::grpc::ClientContext* context, const ::alarm_center_video::request& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::alarm_center_video::dev_info>>(get_all_devsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::alarm_center_video::dev_info>> Asyncget_all_devs(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::alarm_center_video::dev_info>>(Asyncget_all_devsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::alarm_center_video::alarm_info>> get_alarming_devs(::grpc::ClientContext* context, const ::alarm_center_video::request& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::alarm_center_video::alarm_info>>(get_alarming_devsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::alarm_center_video::alarm_info>> Asyncget_alarming_devs(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::alarm_center_video::alarm_info>>(Asyncget_alarming_devsRaw(context, request, cq, tag));
    }
    virtual ::grpc::Status insert_history_record(::grpc::ClientContext* context, const ::alarm_center_video::hisroty_record& request, ::alarm_center_video::reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::alarm_center_video::reply>> Asyncinsert_history_record(::grpc::ClientContext* context, const ::alarm_center_video::hisroty_record& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::alarm_center_video::reply>>(Asyncinsert_history_recordRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientReaderInterface< ::alarm_center_video::dev_info>* get_all_devsRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::alarm_center_video::dev_info>* Asyncget_all_devsRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientReaderInterface< ::alarm_center_video::alarm_info>* get_alarming_devsRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::alarm_center_video::alarm_info>* Asyncget_alarming_devsRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::alarm_center_video::reply>* Asyncinsert_history_recordRaw(::grpc::ClientContext* context, const ::alarm_center_video::hisroty_record& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::alarm_center_video::dev_info>> get_all_devs(::grpc::ClientContext* context, const ::alarm_center_video::request& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::alarm_center_video::dev_info>>(get_all_devsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::alarm_center_video::dev_info>> Asyncget_all_devs(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::alarm_center_video::dev_info>>(Asyncget_all_devsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientReader< ::alarm_center_video::alarm_info>> get_alarming_devs(::grpc::ClientContext* context, const ::alarm_center_video::request& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::alarm_center_video::alarm_info>>(get_alarming_devsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::alarm_center_video::alarm_info>> Asyncget_alarming_devs(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::alarm_center_video::alarm_info>>(Asyncget_alarming_devsRaw(context, request, cq, tag));
    }
    ::grpc::Status insert_history_record(::grpc::ClientContext* context, const ::alarm_center_video::hisroty_record& request, ::alarm_center_video::reply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::alarm_center_video::reply>> Asyncinsert_history_record(::grpc::ClientContext* context, const ::alarm_center_video::hisroty_record& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::alarm_center_video::reply>>(Asyncinsert_history_recordRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReader< ::alarm_center_video::dev_info>* get_all_devsRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request) GRPC_OVERRIDE;
    ::grpc::ClientAsyncReader< ::alarm_center_video::dev_info>* Asyncget_all_devsRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    ::grpc::ClientReader< ::alarm_center_video::alarm_info>* get_alarming_devsRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request) GRPC_OVERRIDE;
    ::grpc::ClientAsyncReader< ::alarm_center_video::alarm_info>* Asyncget_alarming_devsRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::alarm_center_video::reply>* Asyncinsert_history_recordRaw(::grpc::ClientContext* context, const ::alarm_center_video::hisroty_record& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_get_all_devs_;
    const ::grpc::RpcMethod rpcmethod_get_alarming_devs_;
    const ::grpc::RpcMethod rpcmethod_insert_history_record_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status get_all_devs(::grpc::ServerContext* context, const ::alarm_center_video::request* request, ::grpc::ServerWriter< ::alarm_center_video::dev_info>* writer);
    virtual ::grpc::Status get_alarming_devs(::grpc::ServerContext* context, const ::alarm_center_video::request* request, ::grpc::ServerWriter< ::alarm_center_video::alarm_info>* writer);
    virtual ::grpc::Status insert_history_record(::grpc::ServerContext* context, const ::alarm_center_video::hisroty_record* request, ::alarm_center_video::reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_get_all_devs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_get_all_devs() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_get_all_devs() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_all_devs(::grpc::ServerContext* context, const ::alarm_center_video::request* request, ::grpc::ServerWriter< ::alarm_center_video::dev_info>* writer) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_all_devs(::grpc::ServerContext* context, ::alarm_center_video::request* request, ::grpc::ServerAsyncWriter< ::alarm_center_video::dev_info>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_get_alarming_devs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_get_alarming_devs() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_get_alarming_devs() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_alarming_devs(::grpc::ServerContext* context, const ::alarm_center_video::request* request, ::grpc::ServerWriter< ::alarm_center_video::alarm_info>* writer) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_alarming_devs(::grpc::ServerContext* context, ::alarm_center_video::request* request, ::grpc::ServerAsyncWriter< ::alarm_center_video::alarm_info>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_insert_history_record : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_insert_history_record() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_insert_history_record() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status insert_history_record(::grpc::ServerContext* context, const ::alarm_center_video::hisroty_record* request, ::alarm_center_video::reply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestinsert_history_record(::grpc::ServerContext* context, ::alarm_center_video::hisroty_record* request, ::grpc::ServerAsyncResponseWriter< ::alarm_center_video::reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_get_all_devs<WithAsyncMethod_get_alarming_devs<WithAsyncMethod_insert_history_record<Service > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_get_all_devs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_get_all_devs() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_get_all_devs() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_all_devs(::grpc::ServerContext* context, const ::alarm_center_video::request* request, ::grpc::ServerWriter< ::alarm_center_video::dev_info>* writer) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_get_alarming_devs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_get_alarming_devs() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_get_alarming_devs() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_alarming_devs(::grpc::ServerContext* context, const ::alarm_center_video::request* request, ::grpc::ServerWriter< ::alarm_center_video::alarm_info>* writer) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_insert_history_record : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_insert_history_record() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_insert_history_record() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status insert_history_record(::grpc::ServerContext* context, const ::alarm_center_video::hisroty_record* request, ::alarm_center_video::reply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace alarm_center_video


#endif  // GRPC_alarm_5fcenter_5fvideo_2eproto__INCLUDED
