// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: alarm_center_video.proto
#include "stdafx.h"
#include "alarm_center_video.pb.h"
#include "alarm_center_video.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace alarm_center_video {

static const char* video_service_method_names[] = {
  "/alarm_center_video.video_service/update_db",
  "/alarm_center_video.video_service/is_db_updated",
  "/alarm_center_video.video_service/get_is_show_video_user_mgr_dlg",
  "/alarm_center_video.video_service/get_alarming_devs",
  "/alarm_center_video.video_service/get_updated_bind_infos",
  "/alarm_center_video.video_service/insert_history_record",
  "/alarm_center_video.video_service/delete_camera_info",
};

std::unique_ptr< video_service::Stub> video_service::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< video_service::Stub> stub(new video_service::Stub(channel));
  return stub;
}

video_service::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_update_db_(video_service_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_is_db_updated_(video_service_method_names[1], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_get_is_show_video_user_mgr_dlg_(video_service_method_names[2], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_get_alarming_devs_(video_service_method_names[3], ::grpc::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_get_updated_bind_infos_(video_service_method_names[4], ::grpc::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_insert_history_record_(video_service_method_names[5], ::grpc::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_delete_camera_info_(video_service_method_names[6], ::grpc::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::Status video_service::Stub::update_db(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::alarm_center_video::reply* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_update_db_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::alarm_center_video::reply>* video_service::Stub::Asyncupdate_dbRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::alarm_center_video::reply>(channel_.get(), cq, rpcmethod_update_db_, context, request);
}

::grpc::Status video_service::Stub::is_db_updated(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::alarm_center_video::reply* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_is_db_updated_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::alarm_center_video::reply>* video_service::Stub::Asyncis_db_updatedRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::alarm_center_video::reply>(channel_.get(), cq, rpcmethod_is_db_updated_, context, request);
}

::grpc::Status video_service::Stub::get_is_show_video_user_mgr_dlg(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::alarm_center_video::is_show_mgr_dlg* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_get_is_show_video_user_mgr_dlg_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::alarm_center_video::is_show_mgr_dlg>* video_service::Stub::Asyncget_is_show_video_user_mgr_dlgRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::alarm_center_video::is_show_mgr_dlg>(channel_.get(), cq, rpcmethod_get_is_show_video_user_mgr_dlg_, context, request);
}

::grpc::ClientReader< ::alarm_center_video::alarm_info>* video_service::Stub::get_alarming_devsRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request) {
  return new ::grpc::ClientReader< ::alarm_center_video::alarm_info>(channel_.get(), rpcmethod_get_alarming_devs_, context, request);
}

::grpc::ClientAsyncReader< ::alarm_center_video::alarm_info>* video_service::Stub::Asyncget_alarming_devsRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq, void* tag) {
  return new ::grpc::ClientAsyncReader< ::alarm_center_video::alarm_info>(channel_.get(), cq, rpcmethod_get_alarming_devs_, context, request, tag);
}

::grpc::ClientReader< ::alarm_center_video::bind_info>* video_service::Stub::get_updated_bind_infosRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request) {
  return new ::grpc::ClientReader< ::alarm_center_video::bind_info>(channel_.get(), rpcmethod_get_updated_bind_infos_, context, request);
}

::grpc::ClientAsyncReader< ::alarm_center_video::bind_info>* video_service::Stub::Asyncget_updated_bind_infosRaw(::grpc::ClientContext* context, const ::alarm_center_video::request& request, ::grpc::CompletionQueue* cq, void* tag) {
  return new ::grpc::ClientAsyncReader< ::alarm_center_video::bind_info>(channel_.get(), cq, rpcmethod_get_updated_bind_infos_, context, request, tag);
}

::grpc::ClientWriter< ::alarm_center_video::hisroty_record>* video_service::Stub::insert_history_recordRaw(::grpc::ClientContext* context, ::alarm_center_video::reply* response) {
  return new ::grpc::ClientWriter< ::alarm_center_video::hisroty_record>(channel_.get(), rpcmethod_insert_history_record_, context, response);
}

::grpc::ClientAsyncWriter< ::alarm_center_video::hisroty_record>* video_service::Stub::Asyncinsert_history_recordRaw(::grpc::ClientContext* context, ::alarm_center_video::reply* response, ::grpc::CompletionQueue* cq, void* tag) {
  return new ::grpc::ClientAsyncWriter< ::alarm_center_video::hisroty_record>(channel_.get(), cq, rpcmethod_insert_history_record_, context, response, tag);
}

::grpc::ClientWriter< ::alarm_center_video::camera_info>* video_service::Stub::delete_camera_infoRaw(::grpc::ClientContext* context, ::alarm_center_video::reply* response) {
  return new ::grpc::ClientWriter< ::alarm_center_video::camera_info>(channel_.get(), rpcmethod_delete_camera_info_, context, response);
}

::grpc::ClientAsyncWriter< ::alarm_center_video::camera_info>* video_service::Stub::Asyncdelete_camera_infoRaw(::grpc::ClientContext* context, ::alarm_center_video::reply* response, ::grpc::CompletionQueue* cq, void* tag) {
  return new ::grpc::ClientAsyncWriter< ::alarm_center_video::camera_info>(channel_.get(), cq, rpcmethod_delete_camera_info_, context, response, tag);
}

video_service::Service::Service() {
  (void)video_service_method_names;
  AddMethod(new ::grpc::RpcServiceMethod(
      video_service_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< video_service::Service, ::alarm_center_video::request, ::alarm_center_video::reply>(
          std::mem_fn(&video_service::Service::update_db), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      video_service_method_names[1],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< video_service::Service, ::alarm_center_video::request, ::alarm_center_video::reply>(
          std::mem_fn(&video_service::Service::is_db_updated), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      video_service_method_names[2],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< video_service::Service, ::alarm_center_video::request, ::alarm_center_video::is_show_mgr_dlg>(
          std::mem_fn(&video_service::Service::get_is_show_video_user_mgr_dlg), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      video_service_method_names[3],
      ::grpc::RpcMethod::SERVER_STREAMING,
      new ::grpc::ServerStreamingHandler< video_service::Service, ::alarm_center_video::request, ::alarm_center_video::alarm_info>(
          std::mem_fn(&video_service::Service::get_alarming_devs), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      video_service_method_names[4],
      ::grpc::RpcMethod::SERVER_STREAMING,
      new ::grpc::ServerStreamingHandler< video_service::Service, ::alarm_center_video::request, ::alarm_center_video::bind_info>(
          std::mem_fn(&video_service::Service::get_updated_bind_infos), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      video_service_method_names[5],
      ::grpc::RpcMethod::CLIENT_STREAMING,
      new ::grpc::ClientStreamingHandler< video_service::Service, ::alarm_center_video::hisroty_record, ::alarm_center_video::reply>(
          std::mem_fn(&video_service::Service::insert_history_record), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      video_service_method_names[6],
      ::grpc::RpcMethod::CLIENT_STREAMING,
      new ::grpc::ClientStreamingHandler< video_service::Service, ::alarm_center_video::camera_info, ::alarm_center_video::reply>(
          std::mem_fn(&video_service::Service::delete_camera_info), this)));
}

video_service::Service::~Service() {
}

::grpc::Status video_service::Service::update_db(::grpc::ServerContext* context, const ::alarm_center_video::request* request, ::alarm_center_video::reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status video_service::Service::is_db_updated(::grpc::ServerContext* context, const ::alarm_center_video::request* request, ::alarm_center_video::reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status video_service::Service::get_is_show_video_user_mgr_dlg(::grpc::ServerContext* context, const ::alarm_center_video::request* request, ::alarm_center_video::is_show_mgr_dlg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status video_service::Service::get_alarming_devs(::grpc::ServerContext* context, const ::alarm_center_video::request* request, ::grpc::ServerWriter< ::alarm_center_video::alarm_info>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status video_service::Service::get_updated_bind_infos(::grpc::ServerContext* context, const ::alarm_center_video::request* request, ::grpc::ServerWriter< ::alarm_center_video::bind_info>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status video_service::Service::insert_history_record(::grpc::ServerContext* context, ::grpc::ServerReader< ::alarm_center_video::hisroty_record>* reader, ::alarm_center_video::reply* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status video_service::Service::delete_camera_info(::grpc::ServerContext* context, ::grpc::ServerReader< ::alarm_center_video::camera_info>* reader, ::alarm_center_video::reply* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace alarm_center_video

