//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AlarmCenter.rc
//
#define IDOK2                           2
#define IDC_BUTTON_RESET                2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ALARMCENTER_DIALOG          102
#define IDS_STRING_FM_KICKOUT_INVALID   102
#define IDS_STRING_ILLEGAL_OP           103
#define IDS_STRING_ACCT_NOT_UNIQUE      104
#define IDS_STRING_NO_MORE_MACHINE      105
#define IDS_STRING_NEW_MACHINE          106
#define IDS_STRING_TIME_FORMAT          107
#define IDD_PROPPAGE_LARGE_CHOOSE_ZONE  107
#define IDS_STRING_ZONE                 108
#define IDS_STRING_ALIAS                109
#define IDS_STRING_PROPERTY             110
#define IDS_STRING_CONTACT              111
#define IDS_STRING_ADDRESS              112
#define IDS_STRING_PHONE                113
#define IDS_STRING_PHONE_BK             114
#define IDS_STRING_NULL                 115
#define IDS_STRING_ARM                  116
#define IDS_STRING_DISARM               117
#define IDS_STRING_HALFARM              118
#define IDS_STRING_EMERGENCY            119
#define IDS_STRING_BURGLAR              120
#define IDS_STRING_FIRE                 121
#define IDS_STRING_DURESS               122
#define IDS_STRING_GAS                  123
#define IDS_STRING_WATER                124
#define IDS_STRING_TEMPER               125
#define IDS_STRING_LOWBATTERY           126
#define IDS_STRING_BADBATTERY           127
#define IDR_MAINFRAME                   128
#define IDS_STRING_SOLARDISTURB         128
#define IDD_DIALOG_CONTAINER            129
#define IDS_STRING_DISCONNECT           129
#define IDS_STRING_RECONNECT            130
#define IDB_BITMAP1                     131
#define IDB_BITMAP_NETWORK              131
#define IDS_STRING_485DIS               131
#define IDB_BITMAP_NETWORK1             132
#define IDI_ICON_ARM                    132
#define IDS_STRING_485CONN              132
#define IDI_ICON_DISARM                 133
#define IDS_STRING_DOORRING             133
#define IDI_ICON_NETOK                  134
#define IDS_STRING_UNKNOWNEVENT         134
#define IDI_ICON_NETFAIL                135
#define IDS_STRING_ONLINE               135
#define IDS_STRING_OFFLINE              136
#define IDS_STRING_MACHINE              137
#define IDD_DIALOG_MACHINE              138
#define IDS_STRING_NOZONEMAP            138
#define IDI_ICON1                       139
#define IDI_ICON_EMERGENCY              139
#define IDS_STRING_USERID_NOT_EXISTS    139
#define IDB_BITMAP_BUTTON               140
#define IDS_STRING_USER_NAME_NOT_EXISTS 140
#define IDS_STRING_USER_PASSWD_WRONG    141
#define IDD_DIALOG_MAPVIEW              142
#define IDS_STRING_CONFIRM_QUIT         142
#define IDS_STRING_USER                 143
#define IDD_DIALOG_ALARM_TEXT           144
#define IDS_STRING_LOGIN                144
#define IDD_DIALOG_CSR_ACCT             145
#define IDS_STRING_CLK_CLR_FST          145
#define IDD_DIALOG_NETWORK              146
#define IDS_STRING_SUCCESS              146
#define IDD_DIALOG_INPUT                147
#define IDS_STRING_FAILED               147
#define IDR_MENU1                       148
#define IDS_STRING_HURRY_CHANGE_PASSWD  148
#define IDD_DIALOG_LOGIN                149
#define IDS_STRING_CANT_DEL_SUPER       149
#define IDS_STRING_TRANSMIT_DISCONN     150
#define IDS_STRING_TRANSMIT_CONN        151
#define IDD_DIALOG_USERMGR              151
#define IDS_STRING_USER_SUPER           152
#define IDD_DIALOG_MACHINE_MGR          152
#define IDS_STRING_USER_ADMIN           153
#define IDR_MENU2                       153
#define IDS_STRING_USER_OPERATOR        154
#define IDD_DIALOG_GROUP_NAME           154
#define IDS_STRING_ID                   155
#define IDD_DIALOG_ADD_MACHINE          155
#define IDS_STRING_USER_NAME            156
#define IDD_DIALOG_EDIT_ZONE            156
#define IDS_STRING_USER_PASSWD          157
#define IDD_DIALOG_ADD_ZONE             157
#define IDS_STRING_PRIORITY             158
#define IDD_DIALOG_CHOOSE_DET_DLG       158
#define IDS_STRING_USERNAME_EXISTS      159
#define IDD_DIALOG_EDIT_MAP             159
#define IDS_STRING_LOGOUT               160
#define IDD_DIALOG_EDIT_CAMERA          160
#define IDS_STRING_WELCOM               161
#define IDD_PROPPAGE_LARGE_CHOOSE_DET   161
#define IDS_STRING_GOODBYE              162
#define IDD_PROPPAGE_LARGE_CHOOSE_MAP   162
#define IDI_ICON_HISTORY                162
#define IDS_STRING_LOCAL_OP             163
#define IDD_DIALOG_CHOOSE_MACHINE       163
#define IDI_ICON_HALFARM                163
#define IDS_STRING_CLR_MSG              164
#define IDD_DIALOG_PROGRESS             164
#define IDS_STRING_GROUP_ROOT           165
#define IDD_DIALOG_DESTROY_PROGRESS     165
#define IDS_STRING_TAB_TEXT_ALARMING    166
#define IDD_DIALOG_RETRIEVE_PROGRESS    166
#define IDS_STRING_YES                  167
#define IDD_DIALOG_HISTORY              167
#define IDS_STRING_NO                   168
#define IDD_DIALOG_QUERY_ALL_SUBMACHINE 168
#define IDS_STRING_MOVE_TO              169
#define IDD_DIALOG_RESTORE_MACHINE      169
#define IDS_STRING_TYPE_MAP             170
#define IDD_DIALOG_EXTEND_EXPIRE_TIME   170
#define IDS_STRING_TYPE_VIDEO           171
#define IDD_DIALOG_REMIND_QUERY         171
#define IDS_STRING_FM_BANNED            172
#define IDD_DIALOG_QUERY_DISCONN_SUBMACHINE 172
#define IDS_STRING_FM_UNBANNED          173
#define IDD_DIALOG_BAIDU_MAP            173
#define IDS_STRING_FM_TYPE              174
#define IDD_DIALOG_PICK_MACHINE_COOR    174
#define IDS_STRING_GROUP                175
#define IDD_DIALOG1                     175
#define IDS_STRING_GROUP_ADD_SUB        176
#define IDD_DIALOG_SUBMACHINE_EXPIRE_MANAGER 176
#define IDS_STRING_GROUP_DEL            177
#define IDD_DIALOG_AUTO_RETRIEVE_ZONE_INFO 177
#define IDS_STRING_GROUP_REN            178
#define IDD_DIALOG_SMS_CONFIG           178
#define IDS_STRING_GROUP_MOV            179
#define IDD_DIALOG_EXPORT_HR_PROGRESS   179
#define IDS_STRING_ERR_AID              180
#define IDD_DIALOG_MANUALY_ADD_ZONE_WRITE_2_MACHINE 180
#define IDS_STRING_MACHINE_STATUS       181
#define IDS_STRING_SUBMACHINE           182
#define IDB_BITMAP_OFFLINE_ARM          182
#define IDS_STRING_SENSOR               183
#define IDB_BITMAP_OFFLINE_DISARM       183
#define IDS_STRING_ZONE_INFO            184
#define IDB_BITMAP_ONLINE_ARM           184
#define IDS_STRING_SSUBMACHINE          185
#define IDB_BITMAP_ONLINE_DISARM        185
#define IDS_STRING_Q_CHANGE_DET         186
#define IDB_BITMAP_OFFLINE_ARM_HSM      186
#define IDS_STRING_Q_CONFIRM_DEL_SUBMACHINE 187
#define IDB_BITMAP_OFFLINE_DISARM_HSM   187
#define IDS_STRING_Q_CHANGE_SUBMACHINE  188
#define IDB_BITMAP_ONLINE_ARM_HSM       188
#define IDS_STRING_Q_CONFIRM_DEL_DET    189
#define IDB_BITMAP_ONLINE_DISARM_HSM    189
#define IDS_STRING_MAP_INFO             190
#define IDB_BITMAP_GSM_ARM              190
#define IDS_STRING_Q_COMFIRM_DEL_MAP    191
#define IDB_BITMAP_GSM_DISARM           191
#define IDS_STRING_ALL_DET              192
#define IDS_STRING_BIND_DET             193
#define IDD_DIALOG_MGR_VIDEO_USER       193
#define IDS_STRING_UNBIND_DET           194
#define IDS_STRING_Q_NO_MORE_ZONE_TO_BIND 195
#define IDS_STRING_Q_NOT_SM_ZONE        196
#define IDS_STRING_Q_NOT_ZONE_ZONE      197
#define IDS_STRING_MAP                  198
#define IDS_STRING_I_NO_MAP             199
#define IDS_STRING_WIZARD_ADD_DET       200
#define IDS_STRING_NO_CHOOSE_ZONE       201
#define IDS_STRING_NO_CHOOSE_DET        202
#define IDS_STRING_NO_CHOOSE_MAP        203
#define IDS_STRING_ACCELERATOR          204
#define IDS_STRING_A                    205
#define IDS_STRING_UP                   206
#define IDS_STRING_DOWN                 207
#define IDS_STRING_LEFT                 208
#define IDS_STRING_RIGHT                209
#define IDS_STRING_ADD                  210
#define IDS_STRING_SUB                  211
#define IDS_STRING_S                    212
#define IDS_STRING_HAS_SUB_MACHINE      213
#define IDS_STRING_INDEX                214
#define IDS_STRING_TIME                 215
#define IDS_STRING_HISTORY_RECORD       216
#define IDS_STRING_E_NO_EXECEL          217
#define IDS_STRING_E_CREATE_EXCEL       218
#define IDS_STRING_FM_EXCEL_OK          219
#define IDS_STRING_QUERY_REPLACE        220
#define IDS_STRING_NO_SELD_CONTENT      221
#define IDS_STRING_E_TOOLMANY_FIELD     222
#define IDS_STRING_PRINT_DOC_NAME       223
#define IDS_STRING_TIME_ERROR           224
#define IDS_STRING_TIME_NOT_SET         225
#define IDS_STRING_INVALID_ADEMCO_ID    226
#define IDS_STRING_SLAVE_CONN           227
#define IDS_STRING_DESTROY_START        228
#define IDS_STRING_DONE                 229
#define IDS_STRING_DESTROY_TIMER        230
#define IDS_STRING_DESTROY_CONTAINER    231
#define IDS_STRING_DESTROY_ALARMING     232
#define IDS_STRING_DESTROY_NET          233
#define IDS_STRING_DESTROY_NETWORK      234
#define IDS_STRING_DESTROY_MGR          235
#define IDS_STRING_DESTROY_CFG          236
#define IDS_STRING_DESTROY_RES          237
#define IDS_STRING_DESTROY_USER         238
#define IDS_STRING_DESTROY_SND          239
#define IDS_STRING_DESTROY_HR           240
#define IDS_STRING_DESTROY_QR           241
#define IDS_STRING_FM_REMIND_BK_HR      242
#define IDS_STRING_FM_USER_EXPORT_HR    243
#define IDS_STRING_CONN_HANGUP          244
#define IDS_STRING_CONN_RESUME          245
#define IDS_STRING_SUB_MACHINE_SENSOR_EXCEPTION 246
#define IDS_STRING_SUB_MACHINE_SENSOR_RESUME 247
#define IDS_STRING_SUB_MACHINE_POWER_EXCEPTION 248
#define IDS_STRING_SUB_MACHINE_POWER_RESUME 249
#define IDS_STRING_ALL_SUBMACHINE       250
#define IDS_STRING_BK_BTN               251
#define IDS_STRING_QUERY                252
#define IDS_STRING_MACHINE_BUSY         253
#define IDS_STRING_RETRIEVE             254
#define IDS_STRING_WRITE2MACHINE        255
#define IDS_STRING_ZONE_NO_DUIMA        256
#define IDS_STRING_QUERY_FAILED         257
#define IDS_STRING_START                258
#define IDS_STRING_STOP                 259
#define IDS_STRING_E_MACHINE_NO_SUB     260
#define IDS_STRING_RETRY                261
#define IDS_STRING_RESTORE              262
#define IDS_STRING_RESTORE_FAILD        263
#define IDS_STRING_E_MACHINE_NO_ZONE    264
#define IDS_STRING_EXPIRE               265
#define IDS_STRING_INVALID_DATE         266
#define IDS_STRING_INVALID_TIME         267
#define IDR_HTML_BAIDUMAPDLG            268
#define IDS_STRING_E_SUBZONE_RANGE_FAILE 268
#define IDS_STRING_Q_CONFIRM_DEL_DET_UNBIND 269
#define IDS_STRING_ALARM_CENTER         270
#define IDS_STRING_COORDINATE           271
#define IDS_STRING_E_AUTO_LACATE_FAILED 272
#define IDS_STRING_E_ZONE_RANGE_FAILE   273
#define IDS_STRING_BATTERY_RECOVER      274
#define IDS_STRING_FILE_NOT_EXSITS      275
#define IDS_STRING_OPEN_FILE            276
#define IDS_STRING_EXPIRE_TIME          277
#define IDS_STRING_IF_EXPIRE            278
#define IDS_STRING_EXPIRE_DOC_NAME      279
#define IDS_STRING_USER_STOP_RESTRIEVE  280
#define IDS_STRING_FM_RETRIEVE_OK       281
#define IDS_STRING_FM_RETRIEVE_FAILED   282
#define IDS_STRING_FM_ZONE_ALREADY_EXSISTS 283
#define IDS_STRING_FM_CONFIRM_DEL_MACHINE 284
#define IDS_STRING_WIRE_ZONE_NO_NEED_RESTORE 285
#define IDS_STRING_NO_COM               286
#define IDS_STRING_OPEN_COM             287
#define IDS_STRING_CLOSE_COM            288
#define IDS_STRING_TEST                 289
#define IDS_STRING_QUERY_SUCCESS        290
#define IDS_STRING_SYSTEM_EXPORT_HR     291
#define IDS_STRING_BUGLAR_ZONE          292
#define IDS_STRING_FIRE_ZONE            293
#define IDS_STRING_WATER_ZONE           294
#define IDS_STRING_DURESS_ZONE          295
#define IDS_STRING_GAS_ZONE             296
#define IDS_STRING_GLOBAL_ZONE          297
#define IDS_STRING_HALF_ZONE            298
#define IDS_STRING_DOORRING_ZONE        299
#define IDS_STRING_SHIELD_ZONE          300
#define IDS_STRING_EMERGENCY_ZONE       301
#define IDS_STRING_MUTE_ONCE            302
#define IDS_STRING_FM_ZONE_ADDR_NOT_UNIQUE 303
#define IDS_STRING_INPUT_CSR_ACCT       304
#define IDS_STRING_DECIMAL              305
#define IDS_STRING_HEX                  306
#define IDS_STRING_PRODUCTOR            307
#define IDS_STRING_NAME                 308
#define IDS_STRING_ACCT                 309
#define IDD_DIALOG_ADD_VIDEO_USER_EZVIZ 309
#define IDS_STRING_DEVICE_COUNT         310
#define IDD_DIALOG_CHOOSE_ZONE          310
#define IDS_STRING_FM_USERS_DEV_LIST    311
#define IDD_DIALOG_VIDEO_PLAYER         311
#define IDS_STRING_CAMERA_ID            312
#define IDD_DIALOG2                     312
#define IDD_DIALOG_INPUT_VERIFY_CODE    312
#define IDS_STRING_CAMERA_NAME          313
#define IDS_STRING_CAMERA_NO            314
#define IDS_STRING_DEFENCE              315
#define IDS_STRING_DEVICE_ID            316
#define IDS_STRING_DEVICE_NAME          317
#define IDS_STRING_DEVICE_SERIAL        318
#define IDS_STRING_IS_ENCRYPT           319
#define IDS_STRING_IS_SHARED            320
#define IDS_STRING_PIC_URL              321
#define IDS_STRING_STATUS               322
#define IDS_STRING_NOTE                 323
#define IDS_STRING_DEVICE_DOMAIN        324
#define IDS_STRING_DEVICE_IP            325
#define IDS_STRING_DEVICE_PORT          326
#define IDS_STRING_DEVICE_LIST          327
#define IDS_STRING_FM_CONFIRM_DEL_VIDEO_USER 328
#define IDS_STRING_CONFIRM_DEL_VIDEO_USER 328
#define IDS_STRING_PHONE_ALREADY_EXISTS 329
#define IDS_STRING_PRIVATE_CLOUD_CONN_FAIL_OR_USER_NOT_EXSIST 330
#define IDS_STRING_BIND_ZONE            331
#define IDS_STRING_UNBIND_ZONE          332
#define IDS_STRING_DEVICE_CODE_INVALID  333
#define IDS_STRING_UPDATE_CAMERA_INFO_FAILED 334
#define IDS_STRING_PLAY_EXCEPTION       335
#define IDS_STRING_VERIFY_CODE_WRONG    336
#define IDS_STRING_DEVICE_OFFLINE       337
#define IDS_STRING_DESTROY_VIDEO        338
#define IDS_STRING_FM_CAPTURE_OK        339
#define IDS_STRING_EZVIZ                340
#define IDS_STRING_EZVIZ_DESC           341
#define IDS_STRING_HRLV_STATUS          342
#define IDS_STRING_HRLV_USER_LOG        343
#define IDD_DIALOG_CHOOSE_VIDEO_DEVICE  343
#define IDS_STRING_HRLV_USER_EDIT       344
#define IDD_DIALOG_EDIT_DETECTOR        344
#define IDS_STRING_HRLV_USER_CONTROL    345
#define IDS_STRING_HRLV_SYSTEM          346
#define IDS_STRING_HRLV_ALARM           347
#define IDS_STRING_HRLV_EXCEPTION       348
#define IDS_STRING_HRLV_VIDEO           349
#define IDS_STRING_VIDEO_START          350
#define IDD_PROPPAGE_LARGE_CHOOSE_CAMERA 350
#define IDS_STRING_VIDEO_STOP           351
#define IDS_STRING_PLAY_VIDEO           352
#define IDS_STRING_OPEN_FOLDER          353
#define IDB_BITMAP_ONLINE_HALFARM       353
#define IDS_STRING_HRLV                 354
#define IDS_STRING_BIND_VIDEO_DEVICE    355
#define IDB_BITMAP_ONLINE_HALFARM_HSM   355
#define IDS_STRING_VTDU_TIMEOUT         356
#define IDB_BITMAP_OFFLINE_HALFARM_HSM  356
#define IDS_STRING_SEE_BAIDU_MAP        357
#define IDS_STRING_CLR_ALM_MSG          358
#define IDB_BITMAP_OFFLINE_HALFARM      358
#define IDS_STRING_WIZARD_ADD_CAMERA    359
#define IDB_BITMAP_GSM_HALFARM          359
#define IDS_STRING_NO_CHOOSE_CAMERA     360
#define IDD_DIALOG3                     361
#define IDD_DIALOG_ADD_VIDEO_USER_PROGRESS 361
#define IDS_STRING_CONN_TO_SERVER_OK    361
#define IDS_STRING_LOST_SERVER_CONN     362
#define IDS_STRING_CONN_TO_SERVERBK_OK  363
#define IDS_STRING_LOST_SERVERBK_CONN   364
#define IDS_STRING_NETMODE_CSR          365
#define IDS_STRING_NETMODE_TRANSMIT     366
#define IDS_STRING_NETMODE_DUAL         367
#define IDS_STRING_NETMODE_NONE         368
#define IDS_STRING_INVALID_PORT         369
#define IDR_MENU3                       369
#define IDS_STRING_ENTER_SMS_MODE       370
#define IDS_STRING_LEAVE_SMS_MODE       371
#define IDS_STRING_PHONE_USER_CANCLE_ALARM 372
#define IDS_STRING_SAME_ACCT_CSR_ALREADY_ONLINE 373
#define IDS_STRING_SAME_POS             374
#define IDS_STRING_NO_POS               375
#define IDS_STRING_STOP_RTRV_BY_OFFLINE 376
#define IDS_STRING_NO_DUIMA_ZONE        377
#define IDS_STRING_RETRIEVE_OVER        378
#define IDS_STRING_STOP_RTRV_BY_SET_MODE 379
#define IDS_STRING_INPUT_PHONE_VERIFY_CODE 380
#define IDS_STRING_ZONE_TEMPER          381
#define IDS_STRING_ZONE_BATTERY_EXCEPTION 382
#define IDS_STRING_ZONE_BATTERY_EXCEPTION_RECOVER 383
#define IDS_STRING_ZONE_OTHER_EXCEPTION 384
#define IDS_STRING_ZONE_OTHER_EXCEPTION_RECOVER 385
#define IDS_STRING_ON_LINE              386
#define IDS_STRING_DIRECT_PATH          387
#define IDS_STRING_TRANSMIT_PATH_1      388
#define IDS_STRING_TRANSMIT_PATH_2      389
#define IDS_STRING_SMS_PATH             390
#define IDS_STRING_OFF_LINE             391
#define IDS_STRING_SMS_ONLINE           392
#define IDS_STRING_SIGNAL_STRENGTH      393
#define IDS_STRING_HASNOT_SUB_MACHINE   394
#define IDS_STRING_SELF                 395
#define IDS_STRING_VTDU_DISCONNECTED_LINK 396
#define IDS_STRING_VTDU_STATUS_452      397
#define IDS_STRING_VTDU_STATUS_491      398
#define IDS_STRING_WILL_CONN_IN_TIME    399
#define IDS_STRING_VTDU_STATUS_454      400
#define IDR_MENU4                       400
#define IDS_STRING_VTDU_STATUS_405      401
#define IDS_STRING_VTDU_STATUS_404      402
#define IDD_DIALOG_CONSUMER_TYPE_MGR    402
#define IDS_STRING_VTDU_STATUS_406      403
#define IDS_STRING_OPERATIONCODE_FAILED 404
#define IDS_STRING_FM_ADEMCO_ID         405
#define IDS_STRING_USER_DEFINE          406
#define IDS_STRING_TYPE                 407
#define IDS_STRING_INPUT_TYPE           408
#define IDR_MENU5                       408
#define IDR_MENU6                       409
#define IDS_STRING_REMIND_TIME          409
#define IDD_DIALOG_ADD_VIDEO_USER_JOVISION 409
#define IDS_STRING_RECEIVABLE           410
#define IDS_STRING_PAID                 411
#define IDD_DIALOG_ADD_VIDEO_DEVICE_JOVISION 411
#define IDS_STRING_OWED                 412
#define IDS_STRING_IS_OWED              413
#define IDD_DIALOG_VIDEO_RECORD_PLAYER  413
#define IDS_STRING_REMIND_TIME_UP       414
#define IDS_STRING_ASK_RE_INPUT         415
#define IDS_STRING_START_VOICE_TALK     416
#define IDS_STRING_STOP_VOICE_TALK      417
#define IDS_STRING_VOLUME               418
#define IDS_STRING_START_VOICE_TALK_FAIL 419
#define IDS_STRING_STOP_VOICE_TALK_FAIL 420
#define IDS_STRING_INIT_EZVIZ_SDK_ERROR 421
#define IDS_STRING_SMS_CODE_ERR         422
#define IDS_STRING_OP_IS_TO_FAST        423
#define IDS_STRING_OP_FAILED_BY_OFFLINE 424
#define IDS_STRING_CONSUMER_T_HOME      425
#define IDS_STRING_CONSUMER_T_SHOP      426
#define IDS_STRING_CONSUMER_T_OFFICE    427
#define IDS_STRING_JOVISION             428
#define IDS_STRING_JOVISION_DESC        429
#define IDS_STRING_ERROR                430
#define IDS_STRING_CANT_BE_EMPTY        431
#define IDS_STRING_ACCESS_TOKEN         432
#define IDS_STRING_TOKEN_TIME           433
#define IDS_STRING_GLOBAL_USER_NAME     434
#define IDS_STRING_GLOBAL_USER_PASSWD   435
#define IDS_STRING_USER_ALREADY_EXISTS  436
#define IDS_STRING_INIT_JOVISION_SDK_FAILED 437
#define IDS_STRING_RELEASE_EZVIZ_SDK    438
#define IDS_STRING_RELEASE_JOVISION_SDK 439
#define IDS_STRING_CONN_BY_SSE          440
#define IDS_STRING_CLOUD_SSE_ID         441
#define IDS_STRING_IP                   442
#define IDS_STRING_PORT                 443
#define IDS_STRING_CONN_FAIL            444
#define IDS_STRING_ENABLE_DECODE_FAIL   445
#define IDS_STRING_ENABLE_PREVIEW_FAIL  446
#define IDS_InitSDKError                447
#define IDS_InitOK                      448
#define IDS_ConnectError                449
#define IDS_Connecting                  450
#define IDS_ConnectOK                   451
#define IDS_ConnectAccessError          452
#define IDS_ConnectNoChannel            453
#define IDS_ConnectTypeError            454
#define IDS_ConnectCountLimit           455
#define IDS_ConnectTimeout              456
#define IDS_DisconnectError             457
#define IDS_ServerStop                  458
#define IDS_DisconnectOK                459
#define IDS_EnableDecodeOK              460
#define IDS_EnableDecodeError           461
#define IDS_EnablePreviewOK             462
#define IDS_EnablePreviewError          463
#define IDS_DisableDecodeOK             464
#define IDS_DisableDecodeError          465
#define IDS_DisablePreviewOK            466
#define IDS_DisablePreviewError         467
#define IDS_StartRecOK                  468
#define IDS_StartRecError               469
#define IDS_StopRecOK                   470
#define IDS_StopRecError                471
#define IDS_StartAudioOK                472
#define IDS_StartAudioError             473
#define IDS_StopAudioOK                 474
#define IDS_StopAudioError              475
#define IDS_GetPictureOK                476
#define IDS_GetYv12DataOK               477
#define IDS_GetPictureError             478
#define IDS_GetYv12DataError            479
#define IDS_CloudSEEID                  480
#define IDS_Port                        481
#define IDS_DeviceName                  482
#define IDS_DeviceType                  483
#define IDS_ChannelNum                  484
#define IDS_GetRecFileListOK            485
#define IDS_GetRecFileListError         486
#define IDS_NoRecFile                   487
#define IDS_Filename                    488
#define IDS_STRING_RESOLV_DOMAIN_FAIL   489
#define IDS_DIALOG_VIDEO_RECORD_PLAYER  490
#define IDS_OK                          491
#define IDS_CANCEL                      492
#define IDS_GET_REC_LIST                493
#define IDS_REC_LIST                    494
#define IDS_OP_LOG                      495
#define IDS_STRING_BINDED_VIDEO         496
#define IDS_STRING_UNBINDED_VIDEO       497
#define IDS_STRING_ADDED_ZONE           498
#define IDS_STRING_DELED_ZONE           499
#define IDS_STRING_ADDED_SUBMACHINE     500
#define IDS_STRING_DELED_SUBMACHINE     501
#define IDS_STRING_ADDED_MACHINE        502
#define IDS_STRING_DELED_MACHINE        503
#define IDS_STRING_INPUT_MACHINE_ID     504
#define IDS_STRING_INPUT_SUBMACHINE_ID  505
#define IDS_STRING_INVALID_ZONE_VALUE   506
#define IDS_STRING_STOP_ALL_VIDEO       507
#define IDS_STRING_ALL_DEVS             508
#define IDC_STATIC_GROUP                1000
#define IDC_STATIC_SYSTIME              1001
#define IDC_STATIC_CONTROL_PANEL        1006
#define IDC_STATIC_CONTENT              1007
#define IDC_STATIC_NET                  1008
#define IDC_STATIC_STATUS               1009
#define IDC_BUTTON_ARM                  1010
#define IDC_BUTTON_DISARM               1011
#define IDC_BUTTON_MACHINE              1011
#define IDC_BUTTON_EMERGENCY            1012
#define IDC_BUTTON_EMERGENCY2           1013
#define IDC_BUTTON_CLEARMSG             1013
#define IDC_BUTTON_EDIT_ZONE            1014
#define IDC_EDIT1                       1015
#define IDC_BUTTON_EDIT_MAP             1015
#define IDC_EDIT2                       1016
#define IDC_BUTTON_EDIT_VIDEO           1016
#define IDC_IPADDRESS1                  1017
#define IDC_EDIT_USER_NAME              1017
#define IDC_EDIT_Y                      1017
#define IDC_BUTTON_SEE_BAIDU_MAP        1017
#define IDC_EDIT_DEFAULT_USER_NAME      1017
#define IDC_TAB1                        1018
#define IDC_EDIT_PHONE                  1018
#define IDC_EDIT4                       1018
#define IDC_IPADDRESS2                  1018
#define IDC_EDIT5                       1019
#define IDC_BUTTON_MANAGE_EXPIRE        1019
#define IDC_EDIT3                       1019
#define IDC_EDIT6                       1020
#define IDC_IPADDRESS3                  1020
#define IDC_EDIT7                       1021
#define IDC_EDIT_USER_PASSWD            1022
#define IDC_EDIT8                       1022
#define IDC_CHECK_LOGBY_USERID          1023
#define IDC_BUTTON_PRINT                1023
#define IDC_EDIT_EXPIRE_TIME            1023
#define IDC_EDIT9                       1023
#define IDC_EDIT_USERID                 1024
#define IDC_EDIT10                      1024
#define IDC_EDIT_REMIND_TIME            1024
#define IDC_STATIC_NOTE_ID              1025
#define IDC_BUTTON_PAGE_FIRST           1025
#define IDC_STATIC_NOTE_NAME            1026
#define IDC_BUTTON_PAGE_PREV            1026
#define IDC_STATIC_NOTE_PASSWD          1027
#define IDC_BUTTON_PAGE_NEXT            1027
#define IDC_BUTTON_USERMGR              1028
#define IDC_BUTTON_PAGE_LAST            1028
#define IDC_BUTTON_SWITCH_USER          1029
#define IDC_STATIC_TRANSMIT_STATUS      1030
#define IDC_STATIC_LOCAL_PORT           1031
#define IDC_EDIT_CUR_USER_ID            1032
#define IDC_EDIT_CUR_USER_NAME          1033
#define IDC_STATIC_G_CSR                1034
#define IDC_STATIC_G_NET                1035
#define IDC_STATIC_G_TIME               1036
#define IDC_STATIC_G_USER               1037
#define IDC_BUTTON_VIEW_QRCODE          1038
#define IDC_EDIT_CUR_USER_PHONE         1039
#define IDC_LIST1                       1039
#define IDC_EDIT_CUR_USER_PRIORITY      1040
#define IDC_BUTTON_CLEAR                1040
#define IDC_LIST_DEVICE                 1040
#define IDC_LIST_ZONE                   1040
#define IDC_LIST3                       1040
#define IDC_BUTTON_UPDATE               1041
#define IDC_BUTTON_MACHINEMGR           1041
#define IDC_LIST_DEVICE2                1041
#define IDC_LIST_SUBZONE                1041
#define IDC_LIST_ALLDEV                 1041
#define IDC_BUTTON_ADD                  1042
#define IDC_STATIC_TRANSMIT_STATUS_BK   1042
#define IDC_BUTTON_DELETE               1043
#define IDC_COMBO_PRIORITY              1044
#define IDC_EDIT_ID                     1045
#define IDC_EDIT_NAME                   1046
#define IDC_BUTTON_CHANGE_PASSWD        1047
#define IDC_EDIT_ID2                    1047
#define IDC_EDIT_NOTE                   1047
#define IDC_EDIT_PASSWD                 1048
#define IDC_EDIT_CAMERA_NAME            1048
#define IDC_LIST_HISTORY                1049
#define IDC_EDIT_DEVICE_NOTE            1049
#define IDC_EDIT_PASSWD2                1049
#define IDC_TREE_MACHINE_GROUP          1050
#define IDC_TAB_CONTAINER               1051
#define IDC_TREE1                       1052
#define IDC_COMBO1                      1053
#define IDC_COMBO2                      1054
#define IDC_BUTTON_CREATE_MACHINE       1055
#define IDC_BUTTON_CONFIRM_CHANGE       1056
#define IDC_STATIC_NOTE                 1056
#define IDC_BUTTON_DELETE_MACHINE       1057
#define IDC_STATIC_HISTORY              1057
#define IDC_STATIC_NOTE2                1057
#define IDC_COMBO_TYPE                  1058
#define IDC_STATIC_CONN                 1059
#define IDC_STATIC_NOTE3                1059
#define IDC_EDIT_CONTACT                1060
#define IDC_EDIT_ADDRESS                1061
#define IDC_EDIT_PHONE_BK               1063
#define IDC_BUTTON_ADDZONE              1064
#define IDC_BUTTON_DELZONE              1065
#define IDC_STATIC_SUBMACHINE           1066
#define IDC_EDIT_ALIAS                  1067
#define IDC_EDIT_ZONE                   1068
#define IDC_LIST2                       1069
#define IDC_EDIT_MAP                    1069
#define IDC_BUTTON1                     1070
#define IDC_BUTTON_EDIT_DETECTOR        1070
#define IDC_BUTTON_CHANGE_FILE          1070
#define IDC_BUTTON_UNBIND_MAP           1070
#define IDC_BUTTON_SEL_ALL              1070
#define IDC_BUTTON_MUTE                 1070
#define IDC_BUTTON_EXTEND               1070
#define IDC_BUTTON_LOCATE_AUTO          1070
#define IDC_BUTTON_AUTO_LOCATE          1070
#define IDC_BUTTON_START                1070
#define IDC_BUTTON_ADD_MAP              1071
#define IDC_BUTTON_UNBIND_ZONE          1071
#define IDC_BUTTON_SEL_INVERT           1071
#define IDC_BUTTON_SET_PT               1071
#define IDC_BUTTON_DEL_DEVICE           1071
#define IDC_BUTTON_LOCATE_AUTO2         1071
#define IDC_BUTTON_TEST_DOMAIN2         1071
#define IDC_BUTTON_SET_REMIND_TIME      1071
#define IDC_BUTTON_DEL_MAP              1072
#define IDC_BUTTON_BIND_MAP             1072
#define IDC_BUTTON_SEL_NONE             1072
#define IDC_BUTTON_SHOW_PATH            1072
#define IDC_BUTTON_SAVE_DEV             1072
#define IDC_EDIT_FILE                   1073
#define IDC_BUTTON_BIND_ZONE            1073
#define IDC_BUTTON_SHOW_MAP             1073
#define IDC_BUTTON_REFRESH_DEV          1073
#define IDC_STATIC_PREVIEW              1074
#define IDC_COMBO_ANGLE                 1077
#define IDC_BUTTON_ROTATE_UNTICLOCK     1078
#define IDC_BUTTON_ROTATE_CLOCK         1079
#define IDC_BUTTON_DISTANCE_FAR         1080
#define IDC_BUTTON_DISTANCE_NEAR        1081
#define IDC_BUTTON_MOVE_UP              1082
#define IDC_COMBO_SEE                   1083
#define IDC_BUTTON_MOVE_LEFT            1085
#define IDC_BUTTON_SEE_MORE_HR          1085
#define IDC_BUTTON_MOVE_RIGHT           1086
#define IDC_EDIT_ADEMCO_ID              1086
#define IDC_BUTTON_MOVE_DOWN            1087
#define IDC_STATIC_GROUP_HISTORY        1087
#define IDC_BUTTON_ADD_DETECTOR         1088
#define IDC_PROGRESS1                   1088
#define IDC_BUTTON_DEL_DETECTOR         1089
#define IDC_PROGRESS2                   1089
#define IDC_STATIC_TIME                 1090
#define IDC_STATIC_MACHINE_STATUS       1091
#define IDC_STATIC_VER                  1092
#define IDC_STATIC_PROGRESS             1093
#define IDC_BUTTON_MORE_HR              1094
#define IDC_DATETIMEPICKER1             1095
#define IDC_DATETIMEPICKER2             1096
#define IDC_EDIT_X                      1099
#define IDC_LIST_RECORD                 1101
#define IDC_BUTTON_PICK_COOR            1101
#define IDC_PAGE                        1102
#define IDC_BUTTON_MANAGE_SUBMACHINE_EXPIRE_TIME 1102
#define IDC_BUTTON_CLR_HISTORY          1103
#define IDC_BUTTON_ALL                  1103
#define IDC_BUTTON_ALL_NOT              1104
#define IDC_BUTTON_INVERT               1105
#define IDC_BUTTON_MGR_VIDEO_USER       1106
#define IDC_BUTTON_PRINT_SEL            1107
#define IDC_STATIC_LINE_NUM             1108
#define IDC_BUTTON_AUTO_RETRIEVE        1109
#define IDC_BUTTON_CHECK_COM            1110
#define IDC_COMBO_COM                   1111
#define IDC_BUTTON_CONN_GSM             1112
#define IDC_CHECK1                      1113
#define IDC_CHECK2                      1114
#define IDC_CHECK3                      1115
#define IDC_BUTTON_MGR_CAMERA_ICON      1115
#define IDC_BUTTON_CLEAR_CMB            1115
#define IDC_BUTTON_RESTART_APP          1115
#define IDC_CHECK4                      1116
#define IDC_BUTTON_LEFT                 1116
#define IDC_CHECK5                      1117
#define IDC_BUTTON_DOWN                 1117
#define IDC_CHECK6                      1118
#define IDC_BUTTON_RIGHT                1118
#define IDC_BUTTON_MANULLY_ADD_ZONE_WRITE_TO_MACHINE 1119
#define IDC_COMBO3                      1120
#define IDC_COMBO4                      1121
#define IDC_CHECK_AUTO_ALARM            1121
#define IDC_EDIT_PHYSIC_ADDR            1122
#define IDC_CHECK_AUTO_ALARM2           1122
#define IDC_EDIT_DTU_PHONE              1123
#define IDC_STATIC_DEVICE_LIST          1126
#define IDC_LIST_USER                   1127
#define IDC_IPADDRESS_PRIVATE_CLOUD     1128
#define IDC_LIST_USER2                  1128
#define IDC_EDIT_PRIVATE_CLOUD          1129
#define IDC_BUTTON_SAVE_PRIVATE_CLOUD   1130
#define IDC_BUTTON_ADD_USER             1131
#define IDC_IPADDRESS_PRIVATE_CLOUD2    1131
#define IDC_BUTTON_DEL_USER             1132
#define IDC_EDIT_PRIVATE_CLOUD2         1132
#define IDC_BUTTON_SAVE_CHANGE          1133
#define IDC_IPADDRESS_PRIVATE_CLOUD3    1133
#define IDC_EDIT_PRODUCTOR              1134
#define IDC_EDIT_PRIVATE_CLOUD3         1134
#define IDC_BUTTON_REFRESH_DEVICE_LIST  1135
#define IDC_BUTTON_SAVE_SERVER_INFO     1135
#define IDC_EDIT_VERIFY_CODE            1136
#define IDC_EDIT_PRIVATE_CLOUD4         1136
#define IDC_BUTTON_EXPORT               1137
#define IDC_BUTTON_ADD_DEVICE           1137
#define IDC_BUTTON_EXPORT_SEL           1138
#define IDC_BUTTON_BIND_OR_UNBIND       1138
#define IDC_CHECK_AUTO_PLAY_VIDEO       1139
#define IDC_BUTTON_PLAY                 1140
#define IDC_STATIC_PLAYER               1141
#define IDC_BUTTON_UNBIND               1141
#define IDC_RADIO_SMOOTH                1142
#define IDC_RADIO_BALANCE               1143
#define IDC_RADIO_HD                    1144
#define IDC_DATETIMEPICKER_BEG_DATE     1145
#define IDC_BUTTON_STOP                 1145
#define IDC_DATETIMEPICKER_BEG_TIME     1146
#define IDC_BUTTON_CAPTURE              1146
#define IDC_DATETIMEPICKER_END_DATE     1147
#define IDC_BUTTON_UP                   1147
#define IDC_DATETIMEPICKER_END_TIME     1148
#define IDC_BUTTON_BIND_OR_UNBIND_VIDEO_DEVICE 1148
#define IDC_RADIO_SMOOTH2               1148
#define IDC_BUTTON_SEL_BY_DATE          1149
#define IDC_STATIC_SPEED                1149
#define IDC_BUTTON_PREVIEW              1149
#define IDC_COMBO_PER_PAGE              1150
#define IDC_STATIC_PTZ                  1150
#define IDC_STATIC_PER_PAGE             1151
#define IDC_STATIC_CONTROL              1151
#define IDC_RADIO_BALANCE2              1152
#define IDC_BUTTON_SEL_ALARM            1153
#define IDC_CHECK_AUTO_PLAY_VIDEO_ON_ALARM 1153
#define IDC_RADIO_HD2                   1153
#define IDC_BUTTON_SEL_BY_USER          1154
#define IDC_EDIT_DEV_INFO               1154
#define IDC_STATIC_CONTROL2             1154
#define IDC_STATIC_VOICE_TALK           1154
#define IDC_BUTTON_SEL_BY_MACHINE       1155
#define IDC_STATIC_HEX_ADEMCO_ID        1155
#define IDC_STATIC_ALARM                1155
#define IDC_BUTTON_ADD_CEMERA           1156
#define IDC_BUTTON_DEL_CEMERA           1157
#define IDC_RADIO_MODE_CSR              1158
#define IDC_RADIO_MODE_TRANSMIT         1159
#define IDC_RADIO_MODE_DUAL             1160
#define IDC_EDIT_SERVER1_DOMAIN         1161
#define IDC_EDIT_SERVER2_DOMAIN         1162
#define IDC_CHECK_BY_IPPORT1            1163
#define IDC_CHECK_BY_IPPORT2            1164
#define IDC_BUTTON_TEST_DOMAIN1         1165
#define IDC_EDIT_CSRACCT                1166
#define IDC_EDIT_MINUTE                 1167
#define IDC_EDIT_EZVIZ_DOMAIN           1167
#define IDC_BUTTON_SAVE                 1168
#define IDC_BUTTON_TEST_DOMAIN3         1168
#define IDC_STATIC_VIDEO_LIST           1169
#define IDC_CHECK_BY_IPPORT3            1169
#define IDC_STATIC_RECORD_SETTINGS      1170
#define IDC_EDIT_EZVIZ_APP_KEY          1170
#define IDC_STATIC_MINUTE               1171
#define IDC_EDIT_EZVIZ_PORT             1172
#define IDC_COMBO_APP_LANGUAGE          1173
#define IDC_STATIC_REBOOT               1174
#define IDC_BUTTON_GROUP                1175
#define IDC_EDIT_GROUP                  1176
#define IDC_CUSTOM_GRID                 1177
#define IDC_BUTTON_SET_EXPIRE           1177
#define IDC_BUTTON_TYPE_MANAGER         1178
#define IDC_BUTTON_SET_ALARM            1178
#define IDC_EDIT_RECEIVABLE             1179
#define IDC_EDIT_PAID                   1180
#define IDC_STATIC_SELECTED             1180
#define IDC_EDIT_OWED                   1181
#define IDC_BUTTON_SET_TYPE             1181
#define IDC_RADIO_1_VIDEO               1182
#define IDC_RADIO_4_VIDEO               1183
#define IDC_RADIO_9_VIDEO               1184
#define IDC_STATIC_CUR_VIDEO            1185
#define IDC_BUTTON_SPEAKER              1186
#define IDC_SLIDER_VOLUME               1187
#define IDC_STATIC_VLUME                1188
#define IDC_BUTTON_VOICE_TALK           1189
#define IDC_CHECK_VOLUME                1190
#define IDC_TAB_USERS                   1191
#define IDC_STATIC_USER                 1192
#define IDC_EDIT_DEFAULT_USER_PASSWD    1193
#define IDC_EDIT_USER_PHONE             1194
#define IDC_STATIC_TOKEN_OR_NAME        1195
#define IDC_STATIC_TIME_OR_PASSWD       1196
#define IDC_EDIT_TOKEN_OR_NAME          1197
#define IDC_EDIT_TIME_OR_PASSWD         1198
#define IDC_EDIT_CLOUD_SSE_ID           1199
#define IDC_STATIC_DEV_NAME             1200
#define IDC_STATIC_VERIFY_CODE          1201
#define IDC_CHECK_BY_SSE_ID             1202
#define IDC_STATIC_PORT                 1203
#define IDC_STATIC_IP                   1204
#define IDC_EDIT_PORT                   1205
#define IDC_STATIC_USER_NAME            1206
#define IDC_STATIC_USER_PASSWD          1207
#define IDC_STATIC_SSE_ID               1208
#define IDC_BUTTON_REMOTE_CONFIG        1209
#define IDC_BUTTON_OPEN_REC             1210
#define IDC_CHECK_AUTO_PLAY_REC         1211
#define IDC_STATIC_REC_LIST             1212
#define IDC_BUTTON_GET_REC_LIST         1213
#define IDC_STATIC_LOGS                 1214
#define IDC_STATIC_USER_ID              1215
#define IDC_STATIC_MACHINE_ID           1216
#define IDC_BUTTON_STOP_ALL             1217
#define IDC_STATIC_DEVLIST              1218
#define ID_DDD_32771                    32771
#define ID_DDD_32772                    32772
#define ID_DDD_32773                    32773
#define ID_DDD_32774                    32774
#define ID_DDD_32775                    32775
#define ID_Menu                         32776
#define ID_GROUP_32777                  32777
#define ID_GROUP_32778                  32778
#define ID_GROUP_32779                  32779
#define ID_GROUP_ADD                    32780
#define ID_GROUP_DEL                    32781
#define ID_GROUP_RENAME                 32782
#define ID_GROUP_32783                  32783
#define ID_GROUP_EXPIRE_MANAGE          32784
#define ID_DDD_32785                    32785
#define ID_DDD_32786                    32786
#define ID_32787                        32787
#define ID_GROUP_32788                  32788
#define ID_GROUP_32789                  32789
#define ID_SUB_32790                    32790
#define ID_32791                        32791
#define ID_32792                        32792
#define ID_32793                        32793
#define ID_32794                        32794
#define ID_32795                        32795
#define ID_SUB_32796                    32796
#define ID_SUB_32797                    32797
#define ID_SUB_32798                    32798
#define ID_32799                        32799
#define ID_32800                        32800
#define ID_32801                        32801
#define ID_32802                        32802
#define ID_32803                        32803
#define ID_FILTER_ALL                   32804
#define ID_32805                        32805
#define ID_FILTER_ONLINE                32806
#define ID_FILTER_OFFLINE               32807
#define ID_FILTER_ARM                   32808
#define ID_FILTER_DISARM                32809
#define ID_FILTER_EVENT                 32810
#define ID_S_32811                      32811
#define ID_S_32812                      32812
#define ID_S_32813                      32813
#define ID_S_32814                      32814
#define ID_S_DAY                        32815
#define ID_S_WEEK                       32816
#define ID_S_MONTH                      32817
#define ID_S_USER_SET                   32818
#define ID_EXTEND_2                     32819
#define ID_EXTEND_3                     32820
#define ID_EXTEND_4                     32821
#define ID_EXTEND_7                     32822
#define ID_EXTEND_5                     32823
#define ID_EXTEND_6                     32824
#define ID_EXTEND_32825                 32825
#define ID_EXTEND_1_MONTH               32826
#define ID_EXTEND_2_MONTH               32827
#define ID_EXTEND_3_MONTH               32828
#define ID_EXTEND_6_MONTH               32829
#define ID_EXTEND_1_YEAR                32830
#define ID_EXTEND_2_YEAR                32831
#define ID_EXTEND_SET                   32832
#define ID_GROUP_32833                  32833
#define ID_GROUP_CREATE_MACHINE         32834

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        416
#define _APS_NEXT_COMMAND_VALUE         32835
#define _APS_NEXT_CONTROL_VALUE         1219
#define _APS_NEXT_SYMED_VALUE           269
#endif
#endif
